name: Run Python script

on: [ * ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_URI: ${{ secrets.POSTGRES_URI }}
      USERNAME: ${{ secrets.USERNAME }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        run: flask run
